url: http://www.kylawedding.com/
baseurl: ''

# Site settings
title: "#kyla2018"
email: contact@kylawedding.com
description: "Kyle Raney and Kayla DuBois are getting married in Lancaster, KY on July 22, 2018"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 8f3636
  secondary: 908d88  
  secondary-dark: 27181b

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/kaydeanay

# Build settings
markdown: kramdown
permalink: pretty